# Generated by Django 2.0 on 2018-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Event')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('max_slots', models.IntegerField(blank=True, null=True, verbose_name='Max Slots')),
                ('date_from', models.DateField(null=True, verbose_name='Start Date')),
                ('date_to', models.DateField(null=True, verbose_name='End Date')),
                ('time_from', models.TimeField(null=True, verbose_name='Start Time')),
                ('time_to', models.TimeField(null=True, verbose_name='End Time')),
                ('venue', models.CharField(default='', max_length=200, verbose_name='Venue')),
            ],
        ),
    ]
