# Generated by Django 2.0 on 2018-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField(null=True, verbose_name='For Date')),
                ('time_arrived', models.TimeField(blank=True, null=True, verbose_name='Time Arrived')),
                ('time_left', models.TimeField(blank=True, null=True, verbose_name='Time Left')),
                ('security_key', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
