# Generated by Django 2.0 on 2018-11-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Registration'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_arrived',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Arrived'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_left',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Left'),
        ),
    ]
